### PR TITLE
Update 2023-02-04-data-security.md

### PR DESCRIPTION
**Pull request by MeliseRocha**
Adding text explained why using a global variable is not the ideal approach

### CODE REVIEW

**Review by lcsavb — CHANGES_REQUESTED** [review]
It is out of order. The attempt to solve with the global variable should be the first one.

**Comment by MeliseRocha** [comment]
ok

**Review by MeliseRocha — COMMENTED** [review]
Fixed what requested!

**Comment by lcsavb** [comment]
ok

**Pull request merged**
